### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by dragonpoint** [Unity-Technologies/ToolsCollection#2]
I'm not familiar  with python. 
I tried python2.7 and python3.6 both failed
I got following errors when I run "python    buildpackage.py"
Please help!

Traceback (most recent call last):
  File "buildpackage.py", line 7, in <module>
    print subprocess.check_output([sys.argv[1],'-projectPath',os.getcwd(), '-logFile','Bin/Build.log', '-batchmode', '-executeMethod', 'PackageDesigner.CommandLineExportAllPackage', os.getcwd()+'/Bin'])
  File "c:\Python27\lib\subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "c:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 5]

**Comment by MattOstgard** [comment]
I haven't tried but it looks like you need to supply the path to Unity.exe.
